"""approval, irreversible effect and audit trail

Revision ID: 74f132d461a8
Revises:
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "74f132d461a8"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "approval",
        sa.Column("approval_id", sa.String(length=40), nullable=False),
        sa.Column("subject", sa.String(length=200), nullable=False),
        sa.Column("tool", sa.String(length=64), nullable=False),
        sa.Column("account", sa.String(length=64), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("approved_by", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("amount > 0", name="ck_approval_amount_positive"),
        sa.PrimaryKeyConstraint("approval_id"),
    )
    op.create_index("ix_approval_lookup", "approval", ["subject", "tool", "account"], unique=False)
    op.create_table(
        "audit_event",
        sa.Column("audit_id", sa.String(length=40), nullable=False),
        sa.Column(
            "at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("subject", sa.String(length=200), nullable=True),
        sa.Column("token_id", sa.String(length=64), nullable=True),
        sa.Column("tool", sa.String(length=64), nullable=False),
        sa.Column("policy", sa.String(length=16), nullable=False),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.String(length=64), nullable=True),
        sa.Column("required_scope", sa.String(length=64), nullable=True),
        sa.Column("effective_scopes", sa.Text(), nullable=False),
        sa.Column("approval_id", sa.String(length=40), nullable=True),
        sa.Column("effect_id", sa.String(length=40), nullable=True),
        sa.PrimaryKeyConstraint("audit_id"),
    )
    op.create_index("ix_audit_at", "audit_event", ["at"], unique=False)
    op.create_table(
        "irreversible_effect",
        sa.Column("effect_id", sa.String(length=40), nullable=False),
        sa.Column("approval_id", sa.String(length=40), nullable=False),
        sa.Column("subject", sa.String(length=200), nullable=False),
        sa.Column("tool", sa.String(length=64), nullable=False),
        sa.Column("account", sa.String(length=64), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("token_id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["approval_id"],
            ["approval.approval_id"],
        ),
        sa.PrimaryKeyConstraint("effect_id"),
        sa.UniqueConstraint("approval_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("irreversible_effect")
    op.drop_index("ix_audit_at", table_name="audit_event")
    op.drop_table("audit_event")
    op.drop_index("ix_approval_lookup", table_name="approval")
    op.drop_table("approval")
    # ### end Alembic commands ###
