"""rate limit counter

The bucket is the primary key: (subject, tool, window_start). Two subjects cannot share a counter
and neither can two tools, because there is no row for them to share — the isolation the tests
assert is a property of the key rather than of the code above it.

Hand-written rather than autogenerated, and the composite key is the reason: the table exists to
make a bound hold across processes, and a key that silently came out wrong would make the limiter
look right while sharing a bucket between subjects.

Revision ID: b7d2c9e41a08
Revises: 74f132d461a8
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "b7d2c9e41a08"
down_revision: str | None = "74f132d461a8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "rate_limit_counter",
        sa.Column("subject", sa.String(length=200), nullable=False),
        sa.Column("tool", sa.String(length=64), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("subject", "tool", "window_start"),
    )


def downgrade() -> None:
    op.drop_table("rate_limit_counter")
